const data = [
{title1: "Unil",
 cat: {mandat: false, courtmetrage: false, humour: false, live: false, motiondesign: false, vfx: false, drawing: false}, title2: "Après l'Unil",
 year: "2018",
 coprod: "Tohm Studio - Benohit Prod - Unicom - SOC - Unil",
 link: "https://www.youtube.com/embed/D5NxsleKgPg"},
{title1: "Showreel 2023",
 cat: {mandat: false, courtmetrage: false, humour: false, live: false, motiondesign: false, vfx: false, drawing: false}, title2: "Showreel",
 year: "2023",
 coprod: "Tohm Studio",
 link: "https://www.youtube.com/embed/d5sdqU6XnP8"},
{title1: "Hoot",
 cat: {mandat: false, courtmetrage: false, humour: false, live: false, motiondesign: false, vfx: false, drawing: false}, title2: "Montre, Octarine, and CallNight.", year: "2020",
 coprod: "Hoot - Montre - Octarine - CallNight",
 link: "https://www.youtube.com/embed/5iHlYIECJw"},
{title1: "PMI Onboarding",
 cat: {mandat: false, courtmetrage: false, humour: false, live: false, motiondesign: false, vfx: false, drawing: false}, title2: "Onboarding video for PMI.", year: "2019",
 coprod: "PMI",
 link: "https://www.youtube.com/embed/oh2Lsorg298"},
{title1: "tl (Transports Lausannois)", cat: {mandat: false, courtmetrage: false, humour: false, live: false, motiondesign: false, vfx: false, drawing: false}, title2: "Project for Transports Lausannois.", year: "2019",
 coprod: "Transports Lausannois",
 link: "https://www.youtube.com/embed/Qd9yo6J3V3Y"},
{title1: "Tipee1",
 cat: {mandat: false, courtmetrage: false, humour: false, live: false, motiondesign: false, vfx: false, drawing: false}, title2: "First Tipee project.", year: "2018",
 coprod: "Tipee",
 link: "https://www.youtube.com/embed/BQ3REYLuj_s"},
{title1: "Tipee2",
 cat: {mandat: false, courtmetrage: false, humour: false, live: false, motiondesign: false, vfx: false, drawing: false}, title2: "Second Tipee project.", year: "2018",
 coprod: "Tipee",
 link: "https://www.youtube.com/embed/lhlSbgEKMoU"},
{title1: "TFT",
 cat: {mandat: false, courtmetrage: false, humour: false, live: false, motiondesign: false, vfx: false, drawing: false}, title2: "Project for TFT.", year: "2020",
 coprod: "TFT",
 link: "https://www.youtube.com/embed/xEbXkxEQCFo"},
{title1: "Smart Pet Care",
 cat: {mandat: false, courtmetrage: false, humour: false, live: false, motiondesign: false, vfx: false, drawing: false}, title2: "Project for Smart Pet Care.", year: "2019",
 coprod: "Smart Pet Care",
 link: "https://www.youtube.com/embed/zgUBlcSir8Q"},
{title1: "Région Dents Du Midi",
 cat: {mandat: false, courtmetrage: false, humour: false, live: false, motiondesign: false, vfx: false, drawing: false}, title2: "Project for the Région Dents Du Midi.", year: "2021",
 coprod: "Région Dents Du Midi",
 link: "https://www.youtube.com/embed/cQW0SE4Q3qo"},
{title1: "Carte de Voeux Raiffeisen",
 cat: {mandat: false, courtmetrage: false, humour: false, live: false, motiondesign: false, vfx: false, drawing: false}, title2: "Raiffeisen's greeting card project.", year: "2020",
 coprod: "Raiffeisen",
 link: "https://www.youtube.com/embed/Gx7v-uBp3gk"},
{title1: "Odience",
 cat: {mandat: false, courtmetrage: false, humour: false, live: false, motiondesign: false, vfx: false, drawing: false}, title2: "Project for Odience.", year: "2021",
 coprod: "Odience",
 link: "https://www.youtube.com/embed/0eGShTdua4w"},
{title1: "Ketl",
 cat: {mandat: false, courtmetrage: false, humour: false, live: false, motiondesign: false, vfx: false, drawing: false}, title2: "Project Ketl.", year: "2019",
 coprod: "Ketl",
 link: "https://youtube.com/shorts/37mqOt0A7v0?feature=share"},
{title1: "FICC Best Practices",
 cat: {mandat: false, courtmetrage: false, humour: false, live: false, motiondesign: false, vfx: false, drawing: false}, title2: "Best practices before departure by FICC.", year: "2019",
 coprod: "FICC",
 link: "https://www.youtube.com/embed/8AcbeE-Pmmc"},
{title1: "Feng Shui",
 cat: {mandat: false, courtmetrage: false, humour: false, live: false, motiondesign: false, vfx: false, drawing: false}, title2: "Project on Feng Shui.", year: "2018",
 coprod: "Feng Shui",
 link: "https://www.youtube.com/embed/TYs29OsioJY"},
{title1: "Le Farinet",
 cat: {mandat: false, courtmetrage: false, humour: false, live: false, motiondesign: false, vfx: false, drawing: false}, title2: "Project for Le Farinet.", year: "2020",
 coprod: "Le Farinet",
 link: "https://www.youtube.com/embed/llldVODijAc"},
{title1: "La Cité Des Métiers 1",
 cat: {mandat: false, courtmetrage: false, humour: false, live: false, motiondesign: false, vfx: false, drawing: false}, title2: "First video for La Cité Des Métiers.", year: "2019",
 coprod: "La Cité Des Métiers",
 link: "https://www.youtube.com/embed/FaPNlJCw-2Q"},
{title1: "La Cité Des Métiers 2",
 cat: {mandat: false, courtmetrage: false, humour: false, live: false, motiondesign: false, vfx: false, drawing: false}, title2: "Second video for La Cité Des Métiers.", year: "2019",
 coprod: "La Cité Des Métiers",
 link: "https://www.youtube.com/embed/40Kgsu0n-hs"},
{title1: "La Cité Des Métiers 3",
 cat: {mandat: false, courtmetrage: false, humour: false, live: false, motiondesign: false, vfx: false, drawing: false}, title2: "Third video for La Cité Des Métiers.", year: "2019",
 coprod: "La Cité Des Métiers",
 link: "https://www.youtube.com/embed/llxPGopM72s"},
{title1: "La Cité Des Métiers 4",
 cat: {mandat: false, courtmetrage: false, humour: false, live: false, motiondesign: false, vfx: false, drawing: false}, title2: "Fourth video for La Cité Des Métiers.", year: "2019",
 coprod: "La Cité Des Métiers",
 link: "https://www.youtube.com/embed/Kps_nTaXu4Y"},
{title1: "Vagabond - Car Postal",
 cat: {mandat: false, courtmetrage: false, humour: false, live: false, motiondesign: false, vfx: false, drawing: false}, title2: "Project for Vagabond by Car Postal.", year: "2020",
 coprod: "Car Postal",
 link: "https://www.youtube.com/embed/Z5sY9V9SLu0"},
{title1: "BCVs - histoire 1",
 cat: {mandat: false, courtmetrage: false, humour: false, live: false, motiondesign: false, vfx: false, drawing: false}, title2: "First story for BCVs.", year: "2020",
 coprod: "BCVs",
 link: "https://www.youtube.com/embed/hPhpp4zrfjo"},
{title1: "BCVs - histoire 2",
 cat: {mandat: false, courtmetrage: false, humour: false, live: false, motiondesign: false, vfx: false, drawing: false}, title2: "Second story for BCVs.", year: "2020",
 coprod: "BCVs",
 link: "https://youtube.com/shorts/5ZG7TbnVwKk?feature=share"},
{title1: "BCVs",
 cat: {mandat: false, courtmetrage: false, humour: false, live: false, motiondesign: false, vfx: false, drawing: false}, title2: "Project for BCVs.", year: "2020",
 coprod: "BCVs",
 link: "https://youtube.com/shorts/9nDcRM-7HoM?feature=share"},
{title1: "Association Sécurité Riviera",
 cat: {mandat: false, courtmetrage: false, humour: false, live: false, motiondesign: false, vfx: false, drawing: false}, title2: "Project for Association Sécurité Riviera.", year: "2019",
 coprod: "Association Sécurité Riviera",
 link: "https://www.youtube.com/embed/4Hl1to1aJck"},
{title1: "Campagne Enfants Sans Tabac",
 cat: {mandat: false, courtmetrage: false, humour: false, live: false, motiondesign: false, vfx: false, drawing: false}, title2: "Anti-tobacco campaign for children.", year: "2021",
 coprod: "Enfants Sans Tabac",
 link: "https://www.youtube.com/embed/pXNxjOzfDao"},
{title1: "HES-SO 01",
 cat: {mandat: false, courtmetrage: false, humour: false, live: false, motiondesign: false, vfx: false, drawing: false}, title2: "First video for HES-SO.", year: "2020",
 coprod: "HES-SO",
 link: "https://www.youtube.com/embed/zmrEgCidwNg"},
{title1: "HES-SO 02",
 cat: {mandat: false, courtmetrage: false, humour: false, live: false, motiondesign: false, vfx: false, drawing: false}, title2: "Second video for HES-SO.", year: "2020",
 coprod: "HES-SO",
 link: "https://www.youtube.com/embed/PV2gQFnc-aI"},
{title1: "HES-SO 03",
 cat: {mandat: false, courtmetrage: false, humour: false, live: false, motiondesign: false, vfx: false, drawing: false}, title2: "Third video for HES-SO.", year: "2020",
 coprod: "HES-SO",
 link: "https://www.youtube.com/embed/-t7l6AyevVw"},
{title1: "HES-SO 04",
 cat: {mandat: false, courtmetrage: false, humour: false, live: false, motiondesign: false, vfx: false, drawing: false}, title2: "Fourth video for HES-SO.", year: "2020",
 coprod: "HES-SO",
 link: "https://www.youtube.com/embed/-7gLLd9b1DQ"},
{title1: "HES-SO 05",
 cat: {mandat: false, courtmetrage: false, humour: false, live: false, motiondesign: false, vfx: false, drawing: false}, title2: "Fifth video for HES-SO.", year: "2020",
 coprod: "HES-SO",
 link: "https://www.youtube.com/embed/vYUJL-MrmRE"},
{title1: "HES-SO 06",
 cat: {mandat: false, courtmetrage: false, humour: false, live: false, motiondesign: false, vfx: false, drawing: false}, title2: "Sixth video for HES-SO.", year: "2020",
 coprod: "HES-SO",
 link: "https://www.youtube.com/embed/CS8S43ZCgsk"},
{title1: "HES-SO 07",
 cat: {mandat: false, courtmetrage: false, humour: false, live: false, motiondesign: false, vfx: false, drawing: false}, title2: "Seventh video for HES-SO.", year: "2020",
 coprod: "HES-SO",
 link: "https://www.youtube.com/embed/e74Zlh3Q38A"},
{title1: "HES-SO 08",
 cat: {mandat: false, courtmetrage: false, humour: false, live: false, motiondesign: false, vfx: false, drawing: false}, title2: "Eighth video for HES-SO.", year: "2020",
 coprod: "HES-SO",
 link: "https://www.youtube.com/embed/BBtPEHeVx4A"},
{title1: "HES-SO 09",
 cat: {mandat: false, courtmetrage: false, humour: false, live: false, motiondesign: false, vfx: false, drawing: false}, title2: "Ninth video for HES-SO.", year: "2020",
 coprod: "HES-SO",
 link: "https://www.youtube.com/embed/NG4LXmxD07U"},
{title1: "HES-SO 10",
 cat: {mandat: false, courtmetrage: false, humour: false, live: false, motiondesign: false, vfx: false, drawing: false}, title2: "Tenth video for HES-SO.", year: "2020",
 coprod: "HES-SO",
 link: "https://www.youtube.com/embed/E6MfpCTvMaE"},
{title1: "HES-SO 11",
 cat: {mandat: false, courtmetrage: false, humour: false, live: false, motiondesign: false, vfx: false, drawing: false}, title2: "Eleventh video for HES-SO.", year: "2020",
 coprod: "HES-SO",
 link: "https://www.youtube.com/embed/_Gn1eSAl8FE"},
{title1: "HES-SO 12",
 cat: {mandat: false, courtmetrage: false, humour: false, live: false, motiondesign: false, vfx: false, drawing: false}, title2: "Twelfth video for HES-SO.", year: "2020",
 coprod: "HES-SO",
 link: "https://www.youtube.com/embed/3R9VLFGDt9k"},
{title1: "HES-SO 13",
 cat: {mandat: false, courtmetrage: false, humour: false, live: false, motiondesign: false, vfx: false, drawing: false}, title2: "Thirteenth video for HES-SO.", year: "2020",
 coprod: "HES-SO",
 link: "https://www.youtube.com/embed/RKQryYgQHr8"},
{title1: "HES-SO 14",
 cat: {mandat: false, courtmetrage: false, humour: false, live: false, motiondesign: false, vfx: false, drawing: false}, title2: "Fourteenth video for HES-SO.", year: "2020",
 coprod: "HES-SO",
 link: "https://www.youtube.com/embed/ozn2VdNQ94Q"},
{title1: "HES-SO 15",
 cat: {mandat: false, courtmetrage: false, humour: false, live: false, motiondesign: false, vfx: false, drawing: false}, title2: "Fifteenth video for HES-SO.", year: "2020",
 coprod: "HES-SO",
 link: "https://www.youtube.com/embed/aszNZpCeb9Y"},
{title1: "Super Dépanneur 5",
 cat: {mandat: false, courtmetrage: false, humour: false, live: false, motiondesign: false, vfx: false, drawing: false}, title2: "The fifth episode of Super Dépanneur.", year: "2021",
 coprod: "Super Dépanneur",
 link: "https://vimeo.com/356840023?share=copy"},
{title1: "Super Dépanneur 4",
 cat: {mandat: false, courtmetrage: false, humour: false, live: false, motiondesign: false, vfx: false, drawing: false}, title2: "The fourth episode of Super Dépanneur.", year: "2021",
 coprod: "Super Dépanneur",
 link: "https://vimeo.com/356837925?share=copy"},
{title1: "Super Dépanneur 3",
 cat: {mandat: false, courtmetrage: false, humour: false, live: false, motiondesign: false, vfx: false, drawing: false}, title2: "The third episode of Super Dépanneur.", year: "2021",
 coprod: "Super Dépanneur",
 link: "https://vimeo.com/356836443?share=copy"},
{title1: "Super Dépanneur 2",
 cat: {mandat: false, courtmetrage: false, humour: false, live: false, motiondesign: false, vfx: false, drawing: false}, title2: "The second episode of Super Dépanneur.", year: "2021",
 coprod: "Super Dépanneur",
 link: "https://vimeo.com/267378375?share=copy"},
{title1: "Super Dépanneur 1",
 cat: {mandat: false, courtmetrage: false, humour: false, live: false, motiondesign: false, vfx: false, drawing: false}, title2: "The first episode of Super Dépanneur.", year: "2021",
 coprod: "Super Dépanneur",
 link: "https://vimeo.com/267377649?share=copy"},
{title1: "Un Classeur",
 cat: {mandat: false, courtmetrage: false, humour: false, live: false, motiondesign: false, vfx: false, drawing: false}, title2: "Project titled 'Un Classeur'.", year: "2021",
 coprod: "Tohm Studio",
 link: "https://www.youtube.com/watch?v=nDdZ9_tMwi0"},
{title1: "Les Tutos de Jacky",
 cat: {mandat: false, courtmetrage: false, humour: false, live: false, motiondesign: false, vfx: false, drawing: false}, title2: "Jacky's tutorials series.", year: "2021",
 coprod: "Jacky",
 link: "https://www.youtube.com/watch?v=1WeiUK4mEAs&list=PLbuo-NvxrWswfkmC0I7rfSdsrxtKuRB8W"},
{title1: "Les Cosmorégulateurs",
 cat: {mandat: false, courtmetrage: false, humour: false, live: false, motiondesign: false, vfx: false, drawing: false}, title2: "Project 'Les Cosmorégulateurs'.", year: "2021",
 coprod: "Tohm Studio",
 link: "https://www.youtube.com/watch?v=CFcFmURJ3Dk&t=153s"},
{title1: "La Faille Spatiotemporelle",
 cat: {mandat: false, courtmetrage: false, humour: false, live: false, motiondesign: false, vfx: false, drawing: false}, title2: "Project 'La Faille Spatiotemporelle'.", year: "2021",
 coprod: "Tohm Studio",
 link: "https://www.youtube.com/embed/ELXdMZi6B1Y"},
{title1: "Galaxien Coprophage",
 cat: {mandat: false, courtmetrage: false, humour: false, live: false, motiondesign: false, vfx: false, drawing: false}, title2: "Project 'Galaxien Coprophage'.", year: "2021",
 coprod: "Tohm Studio",
 link: "https://www.youtube.com/embed/hQpSbub2up4"},
{title1: "Les Psychosmonautes",
 cat: {mandat: false, courtmetrage: false, humour: false, live: false, motiondesign: false, vfx: false, drawing: false}, title2: "Project 'Les Psychosmonautes'.", year: "2021",
 coprod: "Tohm Studio",
 link: "https://www.youtube.com/embed/xpQeG5-oqww"},
{title1: "Joyeux Noël masqué", cat: {mandat: false, courtmetrage: false, humour: false, live: false, motiondesign: false, vfx: false, drawing: false}, title2: "Masked Christmas project.", year: "2021",
 coprod: "Tohm Studio",
 link: "https://www.youtube.com/embed/ztKWNLZKn3I"},
{title1: "Samegif 8",
 cat: {mandat: false, courtmetrage: false, humour: false, live: false, motiondesign: false, vfx: false, drawing: false}, title2: "The eighth project in the Samegif series.", year: "2021",
 coprod: "Samegif",
 link: "https://www.youtube.com/embed/L7mODMamxWw"},
{title1: "Samegif 3",
 cat: {mandat: false, courtmetrage: false, humour: false, live: false, motiondesign: false, vfx: false, drawing: false}, title2: "The third project in the Samegif series.", year: "2021",
 coprod: "Samegif",
 link: "https://www.youtube.com/embed/ubAuNToXdGY"},
{title1: "Samegif Zombies attack",
 cat: {mandat: false, courtmetrage: false, humour: false, live: false, motiondesign: false, vfx: false, drawing: false}, title2: "Project 'Samegif Zombies attack'.", year: "2021",
 coprod: "Samegif",
 link: "https://www.youtube.com/embed/IQ8w7fdgdJE"},
{title1: "Samegif Paint",
 cat: {mandat: false, courtmetrage: false, humour: false, live: false, motiondesign: false, vfx: false, drawing: false}, title2: "Project 'Samegif Paint'.", year: "2021",
 coprod: "Samegif",
 link: "https://www.youtube.com/embed/tBaC5Z92qCQ"},
{title1: "Rust",
 cat: {mandat: false, courtmetrage: false, humour: false, live: false, motiondesign: false, vfx: false, drawing: false}, title2: "Project 'Rust'.", year: "2021",
 coprod: "Tohm Studio",
 link: "https://www.youtube.com/embed/Na-WFPK-Ots"},
{title1: "3D Chip",
 cat: {mandat: false, courtmetrage: false, humour: false, live: false, motiondesign: false, vfx: false, drawing: false}, title2: "Project '3D Chip'.", year: "2021",
 coprod: "Tohm Studio",
 link: "https://www.youtube.com/embed/jIZVuhQAXNs"},
{title1: "Drink Or Drive",
 cat: {mandat: false, courtmetrage: false, humour: false, live: false, motiondesign: false, vfx: false, drawing: false}, title2: "Project 'Drink Or Drive'.", year: "2021",
 coprod: "Tohm Studio",
 link: "https://www.youtube.com/embed/qX0_ObdpZ5Y"},
{title1: "ATST",
 cat: {mandat: false, courtmetrage: false, humour: false, live: false, motiondesign: false, vfx: false, drawing: false}, title2: "Project 'ATST'.", year: "2021",
 coprod: "Tohm Studio",
 link: "https://www.youtube.com/embed/-9S3ek9R_cQ"},
{title1: "Mr. Inconscient, Morgensters",
 cat: {mandat: false, courtmetrage: false, humour: false, live: false, motiondesign: false, vfx: false, drawing: false}, title2: "Project 'Mr. Inconscient, Morgensters'.", year: "2021",
 coprod: "Tohm Studio",
 link: "https://www.youtube.com/embed/Pp9GRlHalT},
]