const TohmWorks = [
    {
        title1: "Unil",
        cat: {
            explicative: true,
            promo: false,
            motionlivevfx: false,
            illustration: false,
            catcourtmetrge: false,
            exercice: false
        },
        tag: {
            mandat: true,
            tagcourtmetrage: false,
            corpo: true,
            offbeat: false,
            friendly: true,
            live: false,
            motiondesign: true,
            vfx: false,
            drawing: true
        },
        header: "AprÃ¨s l'Unil",
        description: "VidÃ©o de prÃ©sentatio du Service d'Orientation et CarriÃ¨re (SOC) de l'Unil, UniversitÃ© de lausanne.",
        year: 2018,
        client: "Unil",
        prod: "Benohit",
        creative: "Tohm",
        intervenant: "Unicom, SOC",
        link: [{ host: "youtube", link: "https://www.youtube.com/embed/D5NxsleKgPg" }],
        ranking: 5 / 5
    },
    {
        title1: "Showreel 2023",
        cat: {
            explicative: false,
            promo: false,
            motionlivevfx: true,
            illustration: false,
            catcourtmetrge: false,
            exercice: false
        },
        tag: {
            mandat: true,
            tagcourtmetrage: true,
            corpo: true,
            offbeat: false,
            friendly: true,
            live: true,
            motiondesign: true,
            vfx: true,
            drawing: true
        },
        header: "Showreel",
        description: "Bande dÃ©mo de Tohm",
        year: 2023,
        client: "",
        prod: "",
        creative: "Tohm",
        intervenant: "",
        link: [{ host: "youtube", link: "https://www.youtube.com/embed/d5sdqU6XnP8" }],
        ranking: 5 / 5
    },
    {
        title1: "Hoot",
        cat: {
            explicative: false,
            promo: false,
            motionlivevfx: true,
            illustration: false,
            catcourtmetrge: false,
            exercice: false
        },
        tag: {
            mandat: true,
            tagcourtmetrage: false,
            corpo: true,
            offbeat: false,
            friendly: false,
            live: true,
            motiondesign: true,
            vfx: true,
            drawing: false
        },
        header: "",
        description: "prÃ©sentation de services en prise vidÃ©o, retouche numlriques, effets visuels numÃ©riques, montage, motion design, graphisme, habillage sonore et composition musicale",
        year: 2020,
        client: "Hoot",
        prod: "Tohm",
        creative: "Tohm, Octarine, CallNight",
        intervenant: "",
        link: [{ host: "youtube", link: "https://www.youtube.com/embed/-5iHlYIECJw" }],
        ranking: 4 / 5
    },
    {
        title1: "Onboarding",
        cat: {
            explicative: true,
            promo: false,
            motionlivevfx: false,
            illustration: false,
            catcourtmetrge: false,
            exercice: false
        },
        tag: {
            mandat: true,
            tagcourtmetrage: false,
            corpo: true,
            offbeat: false,
            friendly: true,
            live: false,
            motiondesign: true,
            vfx: false,
            drawing: true
        },
        header: "Onboarding video for PMI.",
        description: "",
        year: 2019,
        client: "PMI",
        prod: "Tohm, Benohit",
        creative: "",
        intervenant: "",
        link: [{ host: "youtube", link: "https://www.youtube.com/embed/oh2Lsorg298" }],
        ranking: 5 / 5
    },
    {
        title1: "Tipee",
        cat: {
            explicative: false,
            promo: true,
            motionlivevfx: false,
            illustration: false,
            catcourtmetrge: false,
            exercice: false
        },
        tag: {
            mandat: true,
            tagcourtmetrage: true,
            corpo: true,
            offbeat: false,
            friendly: true,
            live: true,
            motiondesign: true,
            vfx: true,
            drawing: true
        },
        header: "",
        description: "PrÃ©sentation de la plateforme Tipee sous forme de court-mÃ©trage humoristique.",
        year: 2018,
        client: "Tipee",
        prod: "Tohm, Benohit",
        creative: "",
        intervenant: "",
        link: [{ host: "youtube", link: "https://www.youtube.com/embed/BQ3REYLuj_s" }],
        ranking: 3 / 5
    },
    {
        title1: "Tipee",
        cat: {
            explicative: false,
            promo: false,
            motionlivevfx: true,
            illustration: false,
            catcourtmetrge: false,
            exercice: false
        },
        tag: {
            mandat: true,
            tagcourtmetrage: false,
            corpo: true,
            offbeat: false,
            friendly: false,
            live: true,
            motiondesign: true,
            vfx: false,
            drawing: true
        },
        header: "",
        description: "PrÃ©sentation de la plateforme Tipee sous forme de tutoriels avec visuels rÃ©els de l'application animÃ©s.",
        year: 2018,
        client: "Tipee",
        prod: "Tohm, Benohit",
        creative: "",
        intervenant: "",
        link: [{ host: "youtube", link: "https://www.youtube.com/embed/lhlSbgEKMoU" }],
        ranking: 3 / 5
    },
    {
        title1: "TFT",
        cat: {
            explicative: false,
            promo: false,
            motionlivevfx: true,
            illustration: false,
            catcourtmetrge: false,
            exercice: false
        },
        tag: {
            mandat: true,
            tagcourtmetrage: false,
            corpo: true,
            offbeat: false,
            friendly: false,
            live: true,
            motiondesign: true,
            vfx: false,
            drawing: true
        },
        header: "",
        description: "",
        year: 2020,
        client: "",
        prod: "",
        creative: "Tohm",
        intervenant: "",
        link: [{ host: "youtube", link: "https://www.youtube.com/embed/xEbXkxEQCFo" }],
        ranking: 2 / 5
    },
    {
        title1: "Smart Pet Care",
        cat: {
            explicative: false,
            promo: false,
            motionlivevfx: true,
            illustration: false,
            catcourtmetrge: false,
            exercice: false
        },
        tag: {
            mandat: true,
            tagcourtmetrage: false,
            corpo: true,
            offbeat: false,
            friendly: true,
            live: false,
            motiondesign: true,
            vfx: false,
            drawing: true
        },
        header: "",
        description: "PrÃ©sentation du concept et prototype Smart Pet Care.",
        year: 2019,
        client: "",
        prod: "",
        creative: "Smart Pet Care",
        intervenant: "",
        link: [{ host: "youtube", link: "https://www.youtube.com/embed/zgUBlcSir8Q" }],
        ranking: 3 / 5
    },
    {
        title1: "RÃ©gion Dents Du Midi",
        cat: {
            explicative: true,
            promo: false,
            motionlivevfx: false,
            illustration: false,
            catcourtmetrge: false,
            exercice: false
        },
        tag: {
            mandat: true,
            tagcourtmetrage: false,
            corpo: true,
            offbeat: false,
            friendly: true,
            live: true,
            motiondesign: true,
            vfx: true,
            drawing: true
        },
        header: "",
        description: "PrÃ©sentation de la rÃ©forme rÃ©gionnale pour tous les partenaires impliquÃ©s.",
        year: 2021,
        client: "RÃ©gion Dents Du Midi",
        prod: "Benohit, Tohm",
        creative: "",
        intervenant: "",
        link: [{ host: "youtube", link: "https://www.youtube.com/embed/cQW0SE4Q3qo" }],
        ranking: 4 / 5
    },
    {
        title1: "Carte de Voeux Raiffeisen",
        cat: {
            explicative: false,
            promo: false,
            motionlivevfx: false,
            illustration: true,
            catcourtmetrge: false,
            exercice: false
        },
        tag: {
            mandat: true,
            tagcourtmetrage: false,
            corpo: true,
            offbeat: false,
            friendly: true,
            live: false,
            motiondesign: true,
            vfx: false,
            drawing: true
        },
        header: "",
        description: "Carte de voeus, mettant en avant tous les endroits clÃ©s en lien avec la Raiffeisen.",
        year: 2020,
        client: "Raiffeisen",
        prod: "Tohm",
        creative: "",
        intervenant: "",
        link: [{ host: "youtube", link: "https://www.youtube.com/embed/Gx7v-uBp3gk" }],
        ranking: 5 / 5
    },
    {
        title1: "Odience",
        cat: {
            explicative: false,
            promo: false,
            motionlivevfx: true,
            illustration: false,
            catcourtmetrge: false,
            exercice: false
        },
        tag: {
            mandat: true,
            tagcourtmetrage: true,
            corpo: true,
            offbeat: false,
            friendly: true,
            live: true,
            motiondesign: true,
            vfx: true,
            drawing: false
        },
        header: "",
        description: "PublicitÃ© pour le lancement de l'application.",
        year: 2021,
        client: "Odience",
        prod: "",
        creative: "Tohm",
        intervenant: "",
        link: [{ host: "youtube", link: "https://www.youtube.com/embed/0eGShTdua4w" }],
        ranking: 5 / 5
    },
    {
        title1: "Ketl",
        cat: {
            explicative: false,
            promo: false,
            motionlivevfx: true,
            illustration: false,
            catcourtmetrge: false,
            exercice: false
        },
        tag: {
            mandat: true,
            tagcourtmetrage: false,
            corpo: true,
            offbeat: false,
            friendly: false,
            live: false,
            motiondesign: true,
            vfx: false,
            drawing: false
        },
        header: "",
        description: "PrÃ©sentation succinte de l'application Ketl",
        year: 2019,
        client: "Ketl",
        prod: "",
        creative: "Tohm",
        intervenant: "",
        link: [{ host: "youtube", link: "https://www.youtube.com/embed/8AcbeE-Pmmc"}],
        ranking: 5 / 5
    },
    {
        title1: "10 Best Practices Before Departure",
        cat: {
            explicative: true,
            promo: false,
            motionlivevfx: false,
            illustration: false,
            catcourtmetrge: false,
            exercice: false
        },
        tag: {
            mandat: true,
            tagcourtmetrage: true,
            corpo: true,
            offbeat: false,
            friendly: true,
            live: false,
            motiondesign: true,
            vfx: false,
            drawing: true
        },
        header: "",
        description: "Les 10 recommandations pratiques de la FICC pour tous les voyageurs internationaux.",
        year: 2019,
        client: "FICC",
        prod: "Tohm",
        creative: "",
        intervenant: "ACS",
        link: [{ host: "youtube", link: "https://www.youtube.com/embed/VXMJK9AxwX0" }],
        ranking: 4 / 5
    },
    {
        title1: "Feng Shui",
        cat: {
            explicative: false,
            promo: false,
            motionlivevfx: false,
            illustration: false,
            catcourtmetrge: true,
            exercice: false
        },
        tag: {
            mandat: true,
            tagcourtmetrage: true,
            corpo: true,
            offbeat: false,
            friendly: false,
            live: false,
            motiondesign: true,
            vfx: false,
            drawing: true
        },
        header: "",
        description: "Partie narrÃ©e de le vidÃ©o de promotion d'une mÃ©thode Feng Shui.",
        year: 2018,
        client: "",
        prod: "",
        creative: "Tohm",
        intervenant: "",
        link: [{ host: "youtube", link: "https://www.youtube.com/embed/TYs29OsioJY" }],
        ranking: 4 / 5
    },
    {
        title1: "Le Farinet",
        cat: {
            explicative: true,
            promo: false,
            motionlivevfx: false,
            illustration: false,
            catcourtmetrge: false,
            exercice: false
        },
        tag: {
            mandat: true,
            tagcourtmetrage: true,
            corpo: true,
            offbeat: false,
            friendly: true,
            live: true,
            motiondesign: true,
            vfx: true,
            drawing: true
        },
        header: "",
        description: "PrÃ©sentation de la monnaie comlÃ©mentaire locale, son utilitÃ© et son fonctionnement.",
        year: 2016,
        client: "Le Farinet",
        prod: "",
        creative: "Benohit, Tohm",
        intervenant: "",
        link: [{ host: "youtube", link: "https://www.youtube.com/embed/llldVODijAc" }],
        ranking: 5 / 5
    },
    {
        title1: "La CitÃ© Des MÃ©tiers 1",
        cat: {
            explicative: true,
            promo: false,
            motionlivevfx: false,
            illustration: false,
            catcourtmetrge: false,
            exercice: false
        },
        tag: {
            mandat: true,
            tagcourtmetrage: false,
            corpo: true,
            offbeat: false,
            friendly: true,
            live: false,
            motiondesign: true,
            vfx: false,
            drawing: true
        },
        header: "",
        description: "",
        year: 2015,
        client: "La CitÃ© Des MÃ©tiers du Grand GenÃ¨ve",
        prod: "",
        creative: "Benohit, Tohm",
        intervenant: "",
        link: [
            { host: "youtube", link: "https://www.youtube.com/embed/FaPNlJCw-2Q" },
            { host: "youtube", link: "https://www.youtube.com/embed/40Kgsu0n-hs" },
            { host: "youtube", link: "https://www.youtube.com/embed/llxPGopM72s" },
            { host: "youtube", link: "https://www.youtube.com/embed/Kps_nTaXu4Y" }
        ],
        ranking: 4 / 5
    },
    {
        title1: "Vagabond, Car Postal",
        cat: {
            explicative: false,
            promo: true,
            motionlivevfx: false,
            illustration: false,
            catcourtmetrge: false,
            exercice: false
        },
        tag: {
            mandat: true,
            tagcourtmetrage: true,
            corpo: true,
            offbeat: false,
            friendly: true,
            live: false,
            motiondesign: true,
            vfx: false,
            drawing: true
        },
        header: "",
        description: "",
        year: 2020,
        client: "Car Postal",
        prod: "",
        creative: "Tohm",
        intervenant: "",
        link: [{ host: "youtube", link: "https://www.youtube.com/embed/Z5sY9V9SLu0" }],
        ranking: 4 / 5
    },
    {
        title1: "BCVs",
        cat: {
            explicative: false,
            promo: true,
            motionlivevfx: false,
            illustration: false,
            catcourtmetrge: false,
            exercice: false
        },
        tag: {
            mandat: true,
            tagcourtmetrage: true,
            corpo: true,
            offbeat: false,
            friendly: true,
            live: false,
            motiondesign: true,
            vfx: false,
            drawing: true
        },
        header: "",
        description: "",
        year: 2020,
        client: "BCVs",
        prod: "",
        creative: "Benohit, Tohm",
        intervenant: "",
        link: [
            { host: "youtube", link: "https://www.youtube.com/embed/hPhpp4zrfjo" },
            { host: "youtube", link: "https://youtube.com/shorts/5ZG7TbnVwKk?feature=share" },
            { host: "youtube", link: "https://youtube.com/shorts/9nDcRM-7HoM?feature=share" }
        ],
        ranking: 4 / 5
    },
    {
        title1: "Association SÃ©curitÃ© Riviera",
        cat: {
            explicative: false,
            promo: false,
            motionlivevfx: false,
            illustration: true,
            catcourtmetrge: false,
            exercice: false
        },
        tag: {
            mandat: true,
            tagcourtmetrage: false,
            corpo: true,
            offbeat: false,
            friendly: true,
            live: true,
            motiondesign: false,
            vfx: false,
            drawing: true
        },
        header: "Carte de voeux de fin d'annÃ©e.",
        description: "",
        year: 2019,
        client: "Association SÃ©curitÃ© Riviera",
        prod: "",
        creative: "Tohm",
        intervenant: "",
        link: [{ host: "youtube", link: "https://www.youtube.com/embed/4Hl1to1aJck" }],
        ranking: 3 / 5
    },
    {
        title1: "Campagne Enfants Sans Tabac",
        cat: {
            explicative: false,
            promo: true,
            motionlivevfx: false,
            illustration: false,
            catcourtmetrge: false,
            exercice: false
        },
        tag: {
            mandat: true,
            tagcourtmetrage: true,
            corpo: true,
            offbeat: false,
            friendly: true,
            live: false,
            motiondesign: true,
            vfx: false,
            drawing: true
        },
        header: "",
        description: "",
        year: 2021,
        client: "Ligue Pulmonaire Vaudoise, Ligue Vaudoise Contre le Cancer",
        prod: "",
        creative: "Tohm",
        intervenant: "",
        link: [{ host: "youtube", link: "https://www.youtube.com/embed/pXNxjOzfDao" }],
        ranking: 3 / 5
    },
    {
        title1: "HES-SO",
        cat: {
            explicative: true,
            promo: false,
            motionlivevfx: false,
            illustration: false,
            catcourtmetrge: false,
            exercice: false
        },
        tag: {
            mandat: true,
            tagcourtmetrage: true,
            corpo: true,
            offbeat: false,
            friendly: true,
            live: false,
            motiondesign: true,
            vfx: false,
            drawing: true
        },
        header: "HES-SO.",
        description: "RÃ©alisation de 15 vidÃ©os courtes prÃ©sentant les filiÃ¨res de la HES-SO.",
        year: 2020,
        client: "HES-SO",
        prod: "Tohm, Benohit",
        creative: "",
        intervenant: "",
        link: [
            { host: "youtube", link: "https://www.youtube.com/embed/zmrEgCidwNg" },
            { host: "youtube", link: "https://www.youtube.com/embed/PV2gQFnc-aI" },
            { host: "youtube", link: "https://www.youtube.com/embed/-t7l6AyevVw" },
            { host: "youtube", link: "https://www.youtube.com/embed/-7gLLd9b1DQ" },
            { host: "youtube", link: "https://www.youtube.com/embed/vYUJL-MrmRE" },
            { host: "youtube", link: "https://www.youtube.com/embed/CS8S43ZCgsk" },
            { host: "youtube", link: "https://www.youtube.com/embed/e74Zlh3Q38A" },
            { host: "youtube", link: "https://www.youtube.com/embed/BBtPEHeVx4A" },
            { host: "youtube", link: "https://www.youtube.com/embed/NG4LXmxD07U" },
            { host: "youtube", link: "https://www.youtube.com/embed/E6MfpCTvMaE" },
            { host: "youtube", link: "https://www.youtube.com/embed/_Gn1eSAl8FE" },
            { host: "youtube", link: "https://www.youtube.com/embed/3R9VLFGDt9k" },
            { host: "youtube", link: "https://www.youtube.com/embed/RKQryYgQHr8" },
            { host: "youtube", link: "https://www.youtube.com/embed/ozn2VdNQ94Q" },
            { host: "youtube", link: "https://www.youtube.com/embed/aszNZpCeb9Y" }
        ],
        ranking: 3 / 5

    },
    {
        title1: "Super DÃ©panneur 5",
        cat: {
            explicative: false,
            promo: true,
            motionlivevfx: false,
            illustration: false,
            catcourtmetrge: false,
            exercice: false
        },
        tag: {
            mandat: true,
            tagcourtmetrage: true,
            corpo: true,
            offbeat: true,
            friendly: true,
            live: false,
            motiondesign: true,
            vfx: false,
            drawing: true
        },
        header: "",
        description: "",
        year: 2021,
        client: "La Maison du DÃ©pannage",
        prod: "",
        creative: "Benohit, Tohm",
        intervenant: "",
        link: [
            { host: "vimeo", link: "https://player.vimeo.com/video/356840023?share=copy" }, ,
            { host: "vimeo", link: "https://player.vimeo.com/video/356837925?share=copy" },
            { host: "vimeo", link: "https://player.vimeo.com/video/356836443?share=copy" },
            { host: "vimeo", link: "https://player.vimeo.com/video/267378375?share=copy" },
            { host: "vimeo", link: "https://player.vimeo.com/video/267377649?share=copy" }
        ],
        ranking: 5 / 5
    },
    {
        title1: "Un Classeur",
        cat: {
            explicative: false,
            promo: false,
            motionlivevfx: false,
            illustration: false,
            catcourtmetrge: true,
            exercice: false
        },
        tag: {
            mandat: false,
            tagcourtmetrage: true,
            corpo: false,
            offbeat: true,
            friendly: true,
            live: true,
            motiondesign: false,
            vfx: true,
            drawing: false
        },
        header: "",
        description: "",
        year: 2018,
        client: "",
        prod: "",
        creative: "Benohit, Tohm",
        intervenant: "",
        link: [{ host: "youtube", link: "https://www.youtube.com/embed/nDdZ9_tMwi0" }],
        ranking: 5 / 5
    },
    {
        title1: "Les Tutos de Jacky",
        cat: {
            explicative: false,
            promo: false,
            motionlivevfx: false,
            illustration: false,
            catcourtmetrge: true,
            exercice: false
        },
        tag: {
            mandat: false,
            tagcourtmetrage: true,
            corpo: false,
            offbeat: true,
            friendly: true,
            live: true,
            motiondesign: false,
            vfx: true,
            drawing: false
        },
        header: "Photo de profil",
        description: "",
        year: 2021,
        client: "",
        prod: "",
        creative: "Tohm",
        intervenant: "",
        link: [{ host: "youtube", link: "https://www.youtube.com/embed/1WeiUK4mEAs" }],
        ranking: 5 / 5
    },
    {
        title1: "Les CosmorÃ©gulateurs",
        cat: {
            explicative: false,
            promo: false,
            motionlivevfx: false,
            illustration: false,
            catcourtmetrge: true,
            exercice: false
        },
        tag: {
            mandat: false,
            tagcourtmetrage: true,
            corpo: false,
            offbeat: true,
            friendly: true,
            live: true,
            motiondesign: false,
            vfx: true,
            drawing: false
        },
        header: "",
        description: "",
        year: 2008,
        client: "",
        prod: "",
        creative: "Tohm, Benohit",
        intervenant: "",
        link: [{ host: "youtube", link: "https://www.youtube.com/embed/CFcFmURJ3Dk"}],
        ranking: 4 / 5
    },
    {
        title1: "La Faille Spatiotemporelle",
        cat: {
            explicative: false,
            promo: false,
            motionlivevfx: false,
            illustration: false,
            catcourtmetrge: true,
            exercice: false
        },
        tag: {
            mandat: false,
            tagcourtmetrage: true,
            corpo: false,
            offbeat: true,
            friendly: true,
            live: true,
            motiondesign: false,
            vfx: true,
            drawing: false
        },
        header: "",
        description: "",
        year: 2007,
        client: "",
        prod: "",
        creative: "Tohm, Benohit",
        intervenant: "",
        link: [{ host: "youtube", link: "https://www.youtube.com/embed/ELXdMZi6B1Y" }],
        ranking: 3 / 5
    },
    {
        title1: "Galaxien Coprophage",
        cat: {
            explicative: false,
            promo: false,
            motionlivevfx: false,
            illustration: false,
            catcourtmetrge: true,
            exercice: false
        },
        tag: {
            mandat: false,
            tagcourtmetrage: true,
            corpo: false,
            offbeat: true,
            friendly: true,
            live: true,
            motiondesign: false,
            vfx: true,
            drawing: false
        },
        header: "",
        description: "",
        year: 2014,
        client: "",
        prod: "",
        creative: "Tohm, Benohit",
        intervenant: "",
        link: [{ host: "youtube", link: "https://www.youtube.com/embed/hQpSbub2up4" }],
        ranking: 4 / 5
    },
    {
        title1: "Les Psychosmonautes",
        cat: {
            explicative: false,
            promo: false,
            motionlivevfx: false,
            illustration: false,
            catcourtmetrge: true,
            exercice: false
        },
        tag: {
            mandat: false,
            tagcourtmetrage: true,
            corpo: false,
            offbeat: true,
            friendly: true,
            live: true,
            motiondesign: false,
            vfx: true,
            drawing: false
        },
        header: "",
        description: "",
        year: 2012,
        client: "",
        prod: "",
        creative: "Tohm",
        intervenant: "",
        link: [{ host: "youtube", link: "https://www.youtube.com/embed/xpQeG5-oqww" }],
        ranking: 3 / 5
    },
    {
        title1: "Joyeux NoÃ«l masquÃ©",
        cat: {
            explicative: false,
            promo: false,
            motionlivevfx: false,
            illustration: false,
            catcourtmetrge: true,
            exercice: false
        },
        tag: {
            mandat: false,
            tagcourtmetrage: true,
            corpo: false,
            offbeat: true,
            friendly: true,
            live: true,
            motiondesign: false,
            vfx: true,
            drawing: false
        },
        header: "",
        description: "",
        year: 2021,
        client: "",
        prod: "",
        creative: "Tohm",
        intervenant: "",
        link: [{ host: "youtube", link: "https://www.youtube.com/embed/ztKWNLZKn3I" }],
        ranking: 4 / 5
    },
    {
        title1: "Samegif",
        cat: {
            explicative: false,
            promo: false,
            motionlivevfx: false,
            illustration: false,
            catcourtmetrge: false,
            exercice: true
        },
        tag: {
            mandat: false,
            tagcourtmetrage: false,
            corpo: false,
            offbeat: false,
            friendly: false,
            live: false,
            motiondesign: false,
            vfx: false,
            drawing: false
        },
        header: "",
        description: "",
        year: 2021,
        client: "",
        prod: "",
        creative: "Tohm",
        intervenant: "",
        link: [
            { host: "youtube", link: "https://www.youtube.com/embed/ubAuNToXdGY" },
            { host: "youtube", link: "https://www.youtube.com/embed/IQ8w7fdgdJE" },
            { host: "youtube", link: "https://www.youtube.com/embed/tBaC5Z92qCQ" },
            { host: "youtube", link: "https://www.youtube.com/embed/L7mODMamxWw" },
            { host: "youtube", link: "https://www.youtube.com/embed/tBaC5Z92qCQ"}
        ],
        ranking: 3 / 5
    },
    {
        title1: "Rust",
        cat: {
            explicative: false,
            promo: false,
            motionlivevfx: false,
            illustration: false,
            catcourtmetrge: false,
            exercice: true
        },
        tag: {
            mandat: false,
            tagcourtmetrage: false,
            corpo: false,
            offbeat: false,
            friendly: false,
            live: false,
            motiondesign: false,
            vfx: false,
            drawing: false
        },
        header: "",
        description: "",
        year: 2015,
        client: "",
        prod: "",
        creative: "Tohm",
        intervenant: "",
        link: [{ host: "youtube", link: "https://www.youtube.com/embed/Na-WFPK-Ots" }],
        ranking: 1 / 5
    },
    {
        title1: "3D Chip",
        cat: {
            explicative: false,
            promo: false,
            motionlivevfx: false,
            illustration: false,
            catcourtmetrge: false,
            exercice: true
        },
        tag: {
            mandat: false,
            tagcourtmetrage: false,
            corpo: false,
            offbeat: false,
            friendly: false,
            live: false,
            motiondesign: false,
            vfx: false,
            drawing: false
        },
        header: "",
        description: "",
        year: 2016,
        client: "",
        prod: "",
        creative: "Tohm",
        intervenant: "",
        link: [{ host: "youtube", link: "https://www.youtube.com/embed/jIZVuhQAXNs" }],
        ranking: 2 / 5
    },
    {
        title1: "Drink Or Drive",
        cat: {
            explicative: false,
            promo: false,
            motionlivevfx: false,
            illustration: false,
            catcourtmetrge: false,
            exercice: true
        },
        tag: {
            mandat: false,
            tagcourtmetrage: false,
            corpo: false,
            offbeat: false,
            friendly: false,
            live: false,
            motiondesign: false,
            vfx: false,
            drawing: false
        },
        header: "",
        description: "",
        year: 2018,
        client: "",
        prod: "",
        creative: "Tohm",
        intervenant: "",
        link: [{ host: "youtube", link: "https://www.youtube.com/embed/qX0_ObdpZ5Y" }],
        ranking: 3 / 5
    },
    {
        title1: "ATST",
        cat: {
            explicative: false,
            promo: false,
            motionlivevfx: false,
            illustration: false,
            catcourtmetrge: false,
            exercice: true
        },
        tag: {
            mandat: false,
            tagcourtmetrage: false,
            corpo: false,
            offbeat: false,
            friendly: false,
            live: false,
            motiondesign: false,
            vfx: false,
            drawing: false
        },
        header: "",
        description: "",
        year: 2021,
        client: "",
        prod: "",
        creative: "Tohm",
        intervenant: "",
        link: [{ host: "youtube", link: "https://www.youtube.com/embed/-9S3ek9R_cQ" }],
        ranking: 2 / 5
    },
    {
        title1: "Morgenstern",
        cat: {
            explicative: false,
            promo: false,
            motionlivevfx: false,
            illustration: false,
            catcourtmetrge: true,
            exercice: false
        },
        tag: {
            mandat: false,
            tagcourtmetrage: true,
            corpo: false,
            offbeat: false,
            friendly: false,
            live: true,
            motiondesign: false,
            vfx: false,
            drawing: false
        },
        header: "",
        description: "",
        year: 2021,
        client: "",
        prod: "",
        creative: "Tohm",
        intervenant: "Octarine, Bruno Pereira, Mr. Inconscient, Felix Imhof",
        link: [{ host: "youtube", link: "https://www.youtube.com/embed/Pp9GRlHalTY"}],
        ranking: 5 / 5
    },
    {
        title1: "l'Avocat du Diable",
        cat: {
            explicative: false,
            promo: false,
            motionlivevfx: false,
            illustration: false,
            catcourtmetrge: true,
            exercice: false
        },
        tag: {
            mandat: false,
            tagcourtmetrage: true,
            corpo: false,
            offbeat: true,
            friendly: false,
            live: true,
            motiondesign: false,
            vfx: false,
            drawing: false
        },
        header: "Quand une rencontre change rien",
        description: "",
        year: "",
        client: "",
        prod: "",
        creative: "30 Seconds Late",
        intervenant: "48 Hour Film Festival",
        link: [{ host: "youtube", link: "https://www.youtube.com/embed/V4p7FdYQcl8" }],
        ranking: 5 / 5
    },
    {
        title1: "Un EtÃ© Etouffant",
        cat: {
            explicative: false,
            promo: false,
            motionlivevfx: false,
            illustration: false,
            catcourtmetrge: true,
            exercice: false
        },
        tag: {
            mandat: false,
            tagcourtmetrage: true,
            corpo: false,
            offbeat: true,
            friendly: false,
            live: true,
            motiondesign: false,
            vfx: false,
            drawing: false
        },
        header: "",
        description: "",
        year: "2018",
        client: "",
        prod: "",
        creative: "30 Seconds Late",
        intervenant: "48 Hour Film Festival",
        link: [{ host: "youtube", link: "https://www.youtube.com/embed/z4-qzFtt0qQ" }],
        ranking: 5 / 5
    },
    {
        title1: "Un fÃ¼r tuts, tutti pour uno",
        cat: {
            explicative: false,
            promo: false,
            motionlivevfx: false,
            illustration: false,
            catcourtmetrge: true,
            exercice: false
        },
        tag: {
            mandat: false,
            tagcourtmetrage: true,
            corpo: false,
            offbeat: true,
            friendly: false,
            live: true,
            motiondesign: false,
            vfx: false,
            drawing: false
        },
        header: "",
        description: "",
        year: "2020",
        client: "",
        prod: "",
        creative: "30 Seconds Late",
        intervenant: "48 Hour Film Festival",
        link: [{ host: "youtube", link: "https://www.youtube.com/embed/z9MOKYWzZ0U" }],
        ranking: 3 / 5
    },
    {
        title1: "Le Passage",
        cat: {
            explicative: false,
            promo: false,
            motionlivevfx: false,
            illustration: false,
            catcourtmetrge: true,
            exercice: false
        },
        tag: {
            mandat: false,
            tagcourtmetrage: true,
            corpo: false,
            offbeat: true,
            friendly: false,
            live: true,
            motiondesign: false,
            vfx: false,
            drawing: false
        },
        header: "",
        description: "",
        year: "2021",
        client: "",
        prod: "",
        creative: "30 Seconds Late",
        intervenant: "48 Hour Film Festival",
        link: [{ host: "youtube", link: "https://www.youtube.com/embed/UsBaUCicGxc" }],
        ranking: 3 / 5
    },
    {
        title1: "Caca de Licorne",
        cat: {
            explicative: false,
            promo: false,
            motionlivevfx: false,
            illustration: false,
            catcourtmetrge: true,
            exercice: false
        },
        tag: {
            mandat: false,
            tagcourtmetrage: true,
            corpo: false,
            offbeat: true,
            friendly: false,
            live: true,
            motiondesign: false,
            vfx: false,
            drawing: false
        },
        header: "",
        description: "",
        year: "2015",
        client: "",
        prod: "",
        creative: "30 Seconds Late",
        intervenant: "48 Hour Film Festival",
        link: [{ host: "youtube", link: "https://www.youtube.com/embed/RFckMtJa6fA" }],
        ranking: 2 / 5
    },
    {
        title1: "Stress - Legend ft. Nemo",
        cat: {
            explicative: false,
            promo: false,
            motionlivevfx: false,
            illustration: false,
            catcourtmetrge: true,
            exercice: false
        },
        tag: {
            mandat: true,
            tagcourtmetrage: true,
            corpo: false,
            offbeat: false,
            friendly: false,
            live: true,
            motiondesign: false,
            vfx: true,
            drawing: false
        },
        header: "",
        description: "",
        year: "2020",
        client: "Stress Music",
        prod: "Antonin Halm",
        creative: "Tohm VFX",
        intervenant: "",
        link: [{ host: "youtube", link: "https://www.youtube.com/embed/kzt9H6UpUtE" }],
        ranking: 4 / 5
    },
    {
        title1: "Stress - Terre BrÃ»lÃ©e",
        cat: {
            explicative: false,
            promo: false,
            motionlivevfx: false,
            illustration: false,
            catcourtmetrge: true,
            exercice: false
        },
        tag: {
            mandat: true,
            tagcourtmetrage: true,
            corpo: false,
            offbeat: false,
            friendly: false,
            live: true,
            motiondesign: false,
            vfx: true,
            drawing: false
        },
        header: "",
        description: "",
        year: "2019",
        client: "Stress Music",
        prod: "Antonin Halm",
        creative: "Tohm VFX",
        intervenant: "",
        link: [{ host: "youtube", link: "https://www.youtube.com/embed/Bk5fF3BeLkI" }],
        ranking: 5 / 5
    },
    {
        title1: "Luttons Contre le Covid-19",
        cat: {
            explicative: false,
            promo: false,
            motionlivevfx: false,
            illustration: false,
            catcourtmetrge: true,
            exercice: false
        },
        tag: {
            mandat: true,
            tagcourtmetrage: true,
            corpo: false,
            offbeat: true,
            friendly: false,
            live: false,
            motiondesign: false,
            vfx: true,
            drawing: false
        },
        header: "",
        description: "",
        year: "2019",
        client: "",
        prod: "Tohm",
        creative: "",
        intervenant: "",
        link: [{ host: "youtube", link: "https://www.youtube.com/embed/RWCVByE4Xw0" }],
        ranking: 5 / 5
    },
    {
        title1: "Vision 2025",
        cat: {
            explicative: true,
            promo: false,
            motionlivevfx: false,
            illustration: false,
            catcourtmetrge: false,
            exercice: false
        },
        tag: {
            mandat: true,
            tagcourtmetrage: false,
            corpo: true,
            offbeat: false,
            friendly: true,
            live: false,
            motiondesign: true,
            vfx: false,
            drawing: true
        },
        header: "",
        description: "PrÃ©sentation de la Vision 2025 des Transports Lausannois, notamment avec la 'tl touch'. Visionnaire.",
        year: 2019,
        client: "tl",
        prod: "Tohm, Benohit",
        creative: "",
        intervenant: "",
        link: [{ host: "youtube", link: "https://www.youtube.com/embed/Qd9yo6J3V3Y" }],
        ranking: 2 / 5
    },
    {
        title1: "Rainbow Fish",
        cat: {
            explicative: false,
            promo: false,
            motionlivevfx: false,
            illustration: false,
            catcourtmetrge: true,
            exercice: false
        },
        tag: {
            mandat: false,
            tagcourtmetrage: true,
            corpo: false,
            offbeat: false,
            friendly: false,
            live: true,
            motiondesign: false,
            vfx: false,
            drawing: false
        },
        header: "",
        description: "Court-métrage",
        year: 2014,
        client: "tl",
        prod: "Tohm",
        creative: "",
        intervenant: "DOP: Steven Blatter, Actor: F. Milliou, Electro: Mathieu Werlen, Assistant: Valentin Graf, Music: Tohm, Mix&Mastering: Shiverland",
        link: [{ host: "youtube", link: "https://www.youtube.com/embed/NENsJWO3Iog" }],
        ranking: 5 / 5
    }
];