const TohmWorks = [
    {
        title1: "Unil",
        cat: {
            mandat: true,
            courtmetrage: false,
            corpo: true,
            offbeat: false,
            friendly: true,
            live: false,
            motiondesign: true,
            vfx: false,
            drawing: true
        },
        header: "Après l'Unil",
        description: "Vidéo de présentatio du Service d'Orientation et Carrière (SOC) de l'Unil, Université de lausanne.",
        year: 2018,
        client: "Unil",
        prod: "Benohit Prod",
        creative: "Tohm",
        intervenant: "Unicom, SOC",
        link: [{ host: "youtube", link: "https://www.youtube.com/embed/D5NxsleKgPg" }]
    },
    {
        title1: "Showreel 2023",
        cat: {
            mandat: true,
            courtmetrage: true,
            corpo: true,
            offbeat: false,
            friendly: true,
            live: true,
            motiondesign: true,
            vfx: true,
            drawing: true
        },
        header: "Showreel",
        description: "Bande démo de Tohm",
        year: 2023,
        client: "",
        prod: "",
        creative: "Tohm",
        intervenant: "",
        link: [{ host: "youtube", link: "https://www.youtube.com/embed/d5sdqU6XnP8" }]
    },
    {
        title1: "Hoot",
        cat: {
            mandat: true,
            courtmetrage: false,
            corpo: true,
            offbeat: false,
            friendly: false,
            live: true,
            motiondesign: true,
            vfx: true,
            drawing: false
        },
        header: "",
        description: "présentation de services en prise vidéo, retouche numlriques, effets visuels numériques, montage, motion design, graphisme, habillage sonore et composition musicale",
        year: 2020,
        client: "Hoot",
        prod: "Tohm",
        creative: "Tohm, Octarine, CallNight",
        intervenant: "",
        link: [{ host: "youtube", link: "https://www.youtube.com/embed/5iHlYIECJw" }]
    },
    {
        title1: "Onboarding",
        cat: {
            mandat: true,
            courtmetrage: false,
            corpo: true,
            offbeat: false,
            friendly: true,
            live: false,
            motiondesign: true,
            vfx: false,
            drawing: true
        },
        header: "Onboarding video for PMI.",
        description: "",
        year: 2019,
        client: "PMI",
        prod: "Tohm, Benohit",
        creative: "",
        intervenant: "",
        link: [{ host: "youtube", link: "https://www.youtube.com/embed/oh2Lsorg298" }]
    },
    {
        title1: "Vision 2025",
        cat: {
            mandat: true,
            courtmetrage: false,
            corpo: true,
            offbeat: false,
            friendly: true,
            live: false,
            motiondesign: true,
            vfx: false,
            drawing: true
        },
        header: "",
        description: "Présentation de la Vision 2025 des Transports Lausannois, notamment avec la 'tl touch'. Attention : c'est visionnaire...",
        year: 2019,
        client: "tl",
        prod: "Tohm, Benohit",
        creative: "",
        intervenant: "",
        link: [{ host: "youtube", link: "https://www.youtube.com/embed/Qd9yo6J3V3Y" }]
    },
    {
        title1: "Tipee",
        cat: {
            mandat: true,
            courtmetrage: true,
            corpo: true,
            offbeat: false,
            friendly: true,
            live: true,
            motiondesign: true,
            vfx: true,
            drawing: true
        },
        header: "Tipee vidéo 1",
        description: "Présentation de la plateforme Tipee sous forme de court-métrage humoristique.",
        year: 2018,
        client: "Tipee",
        prod: "Tohm, Benohit",
        creative: "",
        intervenant: "",
        link: [{ host: "youtube", link: "https://www.youtube.com/embed/BQ3REYLuj_s" }]
    },
    {
        title1: "Tipee",
        cat: {
            mandat: true,
            courtmetrage: false,
            corpo: true,
            offbeat: false,
            friendly: false,
            live: true,
            motiondesign: true,
            vfx: false,
            drawing: true
        },
        header: "Tipee vidéo 2",
        description: "Présentation de la plateforme Tipee sous forme de tutoriels avec visuels réels de l'application animés.",
        year: 2018,
        client: "Tipee",
        prod: "Tohm, Benohit",
        creative: "",
        intervenant: "",
        link: [{ host: "youtube", link: "https://www.youtube.com/embed/lhlSbgEKMoU" }]
    },
    {
        title1: "TFT",
        cat: {
            mandat: true,
            courtmetrage: false,
            corpo: true,
            offbeat: false,
            friendly: false,
            live: true,
            motiondesign: true,
            vfx: false,
            drawing: true
        },
        header: "",
        description: "",
        year: 2020,
        client: "",
        prod: "",
        creative: "Tohm",
        intervenant: "",
        link: [{ host: "youtube", link: "https://www.youtube.com/embed/xEbXkxEQCFo" }]
    },
    {
        title1: "Smart Pet Care",
        cat: {
            mandat: true,
            courtmetrage: false,
            corpo: true,
            offbeat: false,
            friendly: true,
            live: false,
            motiondesign: true,
            vfx: false,
            drawing: true
        },
        header: "",
        description: "Présentation du concept et prototype Smart Pet Care.",
        year: 2019,
        client: "",
        prod: "",
        creative: "Smart Pet Care",
        intervenant: "",
        link: [{ host: "youtube", link: "https://www.youtube.com/embed/zgUBlcSir8Q" }]
    },
    {
        title1: "Région Dents Du Midi",
        cat: {
            mandat: true,
            courtmetrage: false,
            corpo: true,
            offbeat: false,
            friendly: true,
            live: true,
            motiondesign: true,
            vfx: true,
            drawing: true
        },
        header: "",
        description: "Présentation de la réforme régionnale pour tous les partenaires impliqués.",
        year: 2021,
        client: "",
        prod: "",
        creative: "Région Dents Du Midi",
        intervenant: "",
        link: [{ host: "youtube", link: "https://www.youtube.com/embed/cQW0SE4Q3qo" }]
    },
    {
        title1: "Carte de Voeux Raiffeisen",
        cat: {
            mandat: true,
            courtmetrage: false,
            corpo: true,
            offbeat: false,
            friendly: true,
            live: false,
            motiondesign: true,
            vfx: false,
            drawing: true
        },
        header: "",
        description: "Carte de voeus, mettant en avant tous les endroits clés en lien avec la Raiffeisen.",
        year: 2020,
        client: "",
        prod: "",
        creative: "Raiffeisen",
        intervenant: "",
        link: [{ host: "youtube", link: "https://www.youtube.com/embed/Gx7v-uBp3gk" }]
    },
    {
        title1: "Odience",
        cat: {
            mandat: true,
            courtmetrage: true,
            corpo: true,
            offbeat: false,
            friendly: true,
            live: true,
            motiondesign: true,
            vfx: true,
            drawing: false
        },
        header: "",
        description: "Publicité pour le lancement de l'application.",
        year: 2021,
        client: "",
        prod: "",
        creative: "Odience",
        intervenant: "",
        link: [{ host: "youtube", link: "https://www.youtube.com/embed/0eGShTdua4w" }]
    },
    {
        title1: "Ketl",
        cat: {
            mandat: true,
            courtmetrage: false,
            corpo: true,
            offbeat: false,
            friendly: false,
            live: false,
            motiondesign: true,
            vfx: false,
            drawing: false
        },
        header: "",
        description: "Présentation succinte de l'application Ketl",
        year: 2019,
        client: "",
        prod: "",
        creative: "Ketl",
        intervenant: "",
        link: [{ host: "youtube", link: "https://youtube.com/shorts/37mqOt0A7v0?feature=share" }]
    },
    {
        title1: "10 Best Practices Before Departure",
        cat: {
            mandat: true,
            courtmetrage: true,
            corpo: true,
            offbeat: false,
            friendly: true,
            live: false,
            motiondesign: true,
            vfx: false,
            drawing: true
        },
        header: "",
        description: "Les 10 recommandations pratiques de la FICC pour tous les voyageurs internationaux.",
        year: 2019,
        client: "",
        prod: "",
        creative: "FICC",
        intervenant: "",
        link: [{ host: "youtube", link: "https://www.youtube.com/embed/8AcbeE-Pmmc" }]
    },
    {
        title1: "Feng Shui",
        cat: {
            mandat: true,
            courtmetrage: true,
            corpo: true,
            offbeat: false,
            friendly: false,
            live: false,
            motiondesign: true,
            vfx: false,
            drawing: true
        },
        header: "",
        description: "Partie narrée de le vidéo de promotion d'une méthode Feng Shui.",
        year: 2018,
        client: "",
        prod: "",
        creative: "Tohm",
        intervenant: "",
        link: [{ host: "youtube", link: "https://www.youtube.com/embed/TYs29OsioJY" }]
    },
    {
        title1: "Le Farinet",
        cat: {
            mandat: true,
            courtmetrage: true,
            corpo: true,
            offbeat: false,
            friendly: true,
            live: true,
            motiondesign: true,
            vfx: true,
            drawing: true
        },
        header: "",
        description: "Présentation de la monnaie comlémentaire locale, son utilité et son fonctionnement.",
        year: 2016,
        client: "Le Farinet",
        prod: "",
        creative: "Benohit, Tohm",
        intervenant: "",
        link: [{ host: "youtube", link: "https://www.youtube.com/embed/llldVODijAc" }]
    },
    {
        title1: "La Cité Des Métiers 1",
        cat: {
            mandat: true,
            courtmetrage: false,
            corpo: true,
            offbeat: false,
            friendly: true,
            live: false,
            motiondesign: true,
            vfx: false,
            drawing: true
        },
        header: "",
        description: "",
        year: 2015,
        client: "La Cité Des Métiers du Grand Genève",
        prod: "",
        creative: "Benohit, Tohm",
        intervenant: "",
        link: [
            { host: "youtube", link: "https://www.youtube.com/embed/FaPNlJCw-2Q" },
            { host: "youtube", link: "https://www.youtube.com/embed/40Kgsu0n-hs" },
            { host: "youtube", link: "https://www.youtube.com/embed/llxPGopM72s" },
            { host: "youtube", link: "https://www.youtube.com/embed/Kps_nTaXu4Y" }]
    },
    {
        title1: "Vagabond, Car Postal",
        cat: {
            mandat: true,
            courtmetrage: true,
            corpo: true,
            offbeat: false,
            friendly: true,
            live: false,
            motiondesign: true,
            vfx: false,
            drawing: true
        },
        header: "",
        description: "",
        year: 2020,
        client: "Car Postal",
        prod: "",
        creative: "Tohm",
        intervenant: "",
        link: [{ host: "youtube", link: "https://www.youtube.com/embed/Z5sY9V9SLu0" }]
    },
    {
        title1: "BCVs",
        cat: {
            mandat: true,
            courtmetrage: true,
            corpo: true,
            offbeat: false,
            friendly: true,
            live: false,
            motiondesign: true,
            vfx: false,
            drawing: true
        },
        header: "",
        description: "",
        year: 2020,
        client: "BCVs",
        prod: "",
        creative: "Benohit, Tohm",
        intervenant: "",
        link: [
            { host: "youtube", link: "https://www.youtube.com/embed/hPhpp4zrfjo" },
            { host: "youtube", link: "https://youtube.com/shorts/5ZG7TbnVwKk?feature=share" },
            { host: "youtube", link: "https://youtube.com/shorts/9nDcRM-7HoM?feature=share" }
        ]
    },
    {
        title1: "Association Sécurité Riviera",
        cat: {
            mandat: true,
            courtmetrage: false,
            corpo: true,
            offbeat: false,
            friendly: true,
            live: true,
            motiondesign: false,
            vfx: false,
            drawing: true
        },
        header: "Carte de voeux de fin d'année.",
        description: "",
        year: 2019,
        client: "Association Sécurité Riviera",
        prod: "",
        creative: "Tohm",
        intervenant: "",
        link: [{ host: "youtube", link: "https://www.youtube.com/embed/4Hl1to1aJck" }]
    },
    {
        title1: "Campagne Enfants Sans Tabac",
        cat: {
            mandat: true,
            courtmetrage: true,
            corpo: true,
            offbeat: false,
            friendly: true,
            live: false,
            motiondesign: true,
            vfx: false,
            drawing: true
        },
        header: "",
        description: "",
        year: 2021,
        client: "Ligue Pulmonaire Vaudoise, Ligue Vaudoise Contre le Cancer",
        prod: "",
        creative: "Tohm",
        intervenant: "",
        link: [{ host: "youtube", link: "https://www.youtube.com/embed/pXNxjOzfDao" }]
    },
    {
        title1: "HES-SO",
        cat: {
            mandat: true,
            courtmetrage: true,
            corpo: true,
            offbeat: false,
            friendly: true,
            live: false,
            motiondesign: true,
            vfx: false,
            drawing: true
        },
        header: "HES-SO.",
        description: "Réalisation de 15 vidéos courtes présentant les filières de la HES-SO.",
        year: 2020,
        client: "HES-SO",
        prod: "Tohm, Benohit",
        creative: "",
        intervenant: "",
        link: [{ host: "youtube", link: "https://www.youtube.com/embed/zmrEgCidwNg" },
            { host: "youtube", link: "https://www.youtube.com/embed/PV2gQFnc-aI" },
            { host: "youtube", link: "https://www.youtube.com/embed/-t7l6AyevVw" },
            { host: "youtube", link: "https://www.youtube.com/embed/-7gLLd9b1DQ" },
            { host: "youtube", link: "https://www.youtube.com/embed/vYUJL-MrmRE" },
            { host: "youtube", link: "https://www.youtube.com/embed/CS8S43ZCgsk" },
            { host: "youtube", link: "https://www.youtube.com/embed/e74Zlh3Q38A" },
            { host: "youtube", link: "https://www.youtube.com/embed/BBtPEHeVx4A" },
            { host: "youtube", link: "https://www.youtube.com/embed/NG4LXmxD07U" },
            { host: "youtube", link: "https://www.youtube.com/embed/E6MfpCTvMaE" },
            { host: "youtube", link: "https://www.youtube.com/embed/_Gn1eSAl8FE" },
            { host: "youtube", link: "https://www.youtube.com/embed/3R9VLFGDt9k" },
            { host: "youtube", link: "https://www.youtube.com/embed/RKQryYgQHr8" },
            { host: "youtube", link: "https://www.youtube.com/embed/ozn2VdNQ94Q" },
            { host: "youtube", link: "https://www.youtube.com/embed/aszNZpCeb9Y" }
        ]
    },
    {
        title1: "Super Dépanneur 5",
        cat: {
            mandat: false,
            courtmetrage: false,
            corpo: false,
            offbeat: false,
            friendly: false,
            live: false,
            motiondesign: false,
            vfx: false,
            drawing: false
        },
        header: "",
        description: "",
        year: 2021,
        client: "La Maison du Dépannage",
        prod: "",
        creative: "Benohit, Tohm",
        intervenant: "",
        link: [{ host: "vimeo", link: "https://vimeo.com/356840023?share=copy" },
            { host: "vimeo", link: "https://vimeo.com/356837925?share=copy" },
            { host: "vimeo", link: "https://vimeo.com/356836443?share=copy" },
            { host: "vimeo", link: "https://vimeo.com/267378375?share=copy" },
            { host: "vimeo", link: "https://vimeo.com/267377649?share=copy" }]
    },
    {
        title1: "Un Classeur",
        cat: {
            mandat: false,
            courtmetrage: false,
            corpo: false,
            offbeat: false,
            friendly: false,
            live: false,
            motiondesign: false,
            vfx: false,
            drawing: false
        },
        header: "",
        description: "",
        year: 2018,
        client: "",
        prod: "",
        creative: "Benohit, Tohm",
        intervenant: "",
        link: [{ host: "youtube", link: "https://www.youtube.com/watch?v=nDdZ9_tMwi0" }]
    },
    {
        title1: "Les Tutos de Jacky",
        cat: {
            mandat: false,
            courtmetrage: false,
            corpo: false,
            offbeat: false,
            friendly: false,
            live: false,
            motiondesign: false,
            vfx: false,
            drawing: false
        },
        header: "Photo de profil",
        description: "",
        year: 2021,
        client: "",
        prod: "",
        creative: "Tohm",
        intervenant: "",
        link: [{ host: "youtube", link: "https://www.youtube.com/watch?v=1WeiUK4mEAs&list=PLbuo-NvxrWswfkmC0I7rfSdsrxtKuRB8W" }]
    },
    {
        title1: "Les Cosmorégulateurs",
        cat: {
            mandat: false,
            courtmetrage: false,
            corpo: false,
            offbeat: false,
            friendly: false,
            live: false,
            motiondesign: false,
            vfx: false,
            drawing: false
        },
        header: "",
        description: "",
        year: 2008,
        client: "",
        prod: "",
        creative: "Tohm, Benohit",
        intervenant: "",
        link: [{ host: "youtube", link: "https://www.youtube.com/watch?v=CFcFmURJ3Dk&t=153s" }]
    },
    {
        title1: "La Faille Spatiotemporelle",
        cat: {
            mandat: false,
            courtmetrage: false,
            corpo: false,
            offbeat: false,
            friendly: false,
            live: false,
            motiondesign: false,
            vfx: false,
            drawing: false
        },
        header: "",
        description: "",
        year: 2007,
        client: "",
        prod: "",
        creative: "Tohm, Benohit",
        intervenant: "",
        link: [{ host: "youtube", link: "https://www.youtube.com/embed/ELXdMZi6B1Y" }]
    },
    {
        title1: "Galaxien Coprophage",
        cat: {
            mandat: false,
            courtmetrage: false,
            corpo: false,
            offbeat: false,
            friendly: false,
            live: false,
            motiondesign: false,
            vfx: false,
            drawing: false
        },
        header: "",
        description: "",
        year: 2014,
        client: "",
        prod: "",
        creative: "Tohm, Benohit",
        intervenant: "",
        link: [{ host: "youtube", link: "https://www.youtube.com/embed/hQpSbub2up4" }]
    },
    {
        title1: "Les Psychosmonautes",
        cat: {
            mandat: false,
            courtmetrage: false,
            corpo: false,
            offbeat: false,
            friendly: false,
            live: false,
            motiondesign: false,
            vfx: false,
            drawing: false
        },
        header: "",
        description: "",
        year: 2012,
        client: "",
        prod: "",
        creative: "Tohm",
        intervenant: "",
        link: [{ host: "youtube", link: "https://www.youtube.com/embed/xpQeG5-oqww" }]
    },
    {
        title1: "Joyeux Noël masqué",
        cat: {
            mandat: false,
            courtmetrage: false,
            corpo: false,
            offbeat: false,
            friendly: false,
            live: false,
            motiondesign: false,
            vfx: false,
            drawing: false
        },
        header: "",
        description: "",
        year: 2021,
        client: "",
        prod: "",
        creative: "Tohm",
        intervenant: "",
        link: [{ host: "youtube", link: "https://www.youtube.com/embed/ztKWNLZKn3I" }]
    },
    {
        title1: "Samegif 8",
        cat: {
            mandat: false,
            courtmetrage: false,
            corpo: false,
            offbeat: false,
            friendly: false,
            live: false,
            motiondesign: false,
            vfx: false,
            drawing: false
        },
        header: "",
        description: "",
        year: 2021,
        client: "",
        prod: "",
        creative: "Tohm",
        intervenant: "",
        link: [{ host: "youtube", link: "https://www.youtube.com/embed/L7mODMamxWw" }]
    },
    {
        title1: "Samegif 3",
        cat: {
            mandat: false,
            courtmetrage: false,
            corpo: false,
            offbeat: false,
            friendly: false,
            live: false,
            motiondesign: false,
            vfx: false,
            drawing: false
        },
        header: "",
        description: "",
        year: 2021,
        client: "",
        prod: "",
        creative: "Tohm",
        intervenant: "",
        link: [{ host: "youtube", link: "https://www.youtube.com/embed/ubAuNToXdGY" },
            { host: "youtube", link: "https://www.youtube.com/embed/IQ8w7fdgdJE" },
            { host: "youtube", link: "https://www.youtube.com/embed/tBaC5Z92qCQ" }
        ]
    },
    {
        title1: "Rust",
        cat: {
            mandat: false,
            courtmetrage: false,
            corpo: false,
            offbeat: false,
            friendly: false,
            live: false,
            motiondesign: false,
            vfx: false,
            drawing: false
        },
        header: "",
        description: "",
        year: 2015,
        client: "",
        prod: "",
        creative: "Tohm",
        intervenant: "",
        link: [{ host: "youtube", link: "https://www.youtube.com/embed/Na-WFPK-Ots" }]
    },
    {
        title1: "3D Chip",
        cat: {
            mandat: false,
            courtmetrage: false,
            corpo: false,
            offbeat: false,
            friendly: false,
            live: false,
            motiondesign: false,
            vfx: false,
            drawing: false
        },
        header: "",
        description: "",
        year: 2016,
        client: "",
        prod: "",
        creative: "Tohm",
        intervenant: "",
        link: [{ host: "youtube", link: "https://www.youtube.com/embed/jIZVuhQAXNs" }]
    },
    {
        title1: "Drink Or Drive",
        cat: {
            mandat: false,
            courtmetrage: false,
            corpo: false,
            offbeat: false,
            friendly: false,
            live: false,
            motiondesign: false,
            vfx: false,
            drawing: false
        },
        header: "",
        description: "",
        year: 2018,
        client: "",
        prod: "",
        creative: "Tohm",
        intervenant: "",
        link: [{ host: "youtube", link: "https://www.youtube.com/embed/qX0_ObdpZ5Y" }]
    },
    {
        title1: "ATST",
        cat: {
            mandat: false,
            courtmetrage: false,
            corpo: false,
            offbeat: false,
            friendly: false,
            live: false,
            motiondesign: false,
            vfx: false,
            drawing: false
        },
        header: "",
        description: "",
        year: 2021,
        client: "",
        prod: "",
        creative: "Tohm",
        intervenant: "",
        link: [{ host: "youtube", link: "https://www.youtube.com/embed/-9S3ek9R_cQ" }]
    },
    {
        title1: "Morgenstern",
        cat: {
            mandat: false,
            courtmetrage: false,
            corpo: false,
            offbeat: false,
            friendly: false,
            live: true,
            motiondesign: false,
            vfx: false,
            drawing: false
        },
        header: "",
        description: "",
        year: 2021,
        client: "",
        prod: "",
        creative: "Tohm",
        intervenant: "Octarine, Bruno Pereira, Mr. Inconscient, Felix Imhof",
        link: [{ host: "youtube", link: "https://www.youtube.com/embed/Pp9GRlHalT" }]
    }
];
